-- AlterTable
ALTER TABLE "Content" ALTER COLUMN "created_at_tz" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Record" ALTER COLUMN "created_at_tz" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "CAIndexedAt_tz" SET DEFAULT CURRENT_TIMESTAMP,
ALTER COLUMN "lastUpdatedAt_tz" SET DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "User" ALTER COLUMN "created_at_tz" SET DEFAULT CURRENT_TIMESTAMP;
